// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgn7pfJweCe3S_pN1-1HZQPFkLKtYqww',
    appId: '1:1047276016579:web:ef627d55096bd92742e376',
    messagingSenderId: '1047276016579',
    projectId: 'aplikasi-1-2b404',
    authDomain: 'aplikasi-1-2b404.firebaseapp.com',
    storageBucket: 'aplikasi-1-2b404.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe50N-fuR3PAV0qrUdhKcXV2IPxZzvmYg',
    appId: '1:1047276016579:android:fcea9c1a00fef84042e376',
    messagingSenderId: '1047276016579',
    projectId: 'aplikasi-1-2b404',
    storageBucket: 'aplikasi-1-2b404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvmFPDZddm_KuKk51pICKrCnlqSx2gnz4',
    appId: '1:1047276016579:ios:f6395d69c5cb8af442e376',
    messagingSenderId: '1047276016579',
    projectId: 'aplikasi-1-2b404',
    storageBucket: 'aplikasi-1-2b404.firebasestorage.app',
    iosClientId:
        '1047276016579-rva4hajdrss5q70hfhc72t7si98dmnqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvmFPDZddm_KuKk51pICKrCnlqSx2gnz4',
    appId: '1:1047276016579:ios:f6395d69c5cb8af442e376',
    messagingSenderId: '1047276016579',
    projectId: 'aplikasi-1-2b404',
    storageBucket: 'aplikasi-1-2b404.firebasestorage.app',
    iosClientId:
        '1047276016579-rva4hajdrss5q70hfhc72t7si98dmnqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgn7pfJweCe3S_pN1-1HZQPFkLKtYqww',
    appId: '1:1047276016579:web:754b151eb482402442e376',
    messagingSenderId: '1047276016579',
    projectId: 'aplikasi-1-2b404',
    authDomain: 'aplikasi-1-2b404.firebaseapp.com',
    storageBucket: 'aplikasi-1-2b404.firebasestorage.app',
  );
}
